function generateReadme(scanResult) {

    let output = "";

    output += `# ${scanResult.projectOverview.projectName}\n\n`;

    output += `## Overview\n\n`;

    output += `${scanResult.projectOverview.purpose}\n\n`;



    output += `## Tech Stack\n\n`;

    if (scanResult.techStack.length) {

        scanResult.techStack.forEach(tech => {
            output += `- ${tech}\n`;
        });

    } else {

        output += "- Unknown\n";
    }

    output += "\n";



    output += `## Architecture\n\n`;

    output += `Frontend:\n`;

    if (
        scanResult.projectOverview.architecture.frontend.length
    ) {

        scanResult.projectOverview.architecture.frontend
            .forEach(item => {

                output += `- ${item}\n`;

            });

    }

    output += "\n";

    output += `Backend:\n`;

    if (
        scanResult.projectOverview.architecture.backend.length
    ) {

        scanResult.projectOverview.architecture.backend
            .forEach(item => {

                output += `- ${item}\n`;

            });

    }

    output += "\n";



    output += `## Entry Points\n\n`;

    if (
        scanResult.projectOverview.entryPoints.length
    ) {

        scanResult.projectOverview.entryPoints
            .forEach(entry => {

                output += `- ${entry}\n`;

            });

    }

    output += "\n";



    output += `## Project Structure\n\n`;

    output += "```text\n";

    scanResult.files
        .slice(0, 25)
        .forEach(file => {

            output += `${file.path}\n`;

        });

    output += "```\n\n";



    output += `## Dependencies\n\n`;

    Object.entries(
        scanResult.dependencies.dependencies || {}
    ).forEach(([name, version]) => {

        output += `- ${name} (${version})\n`;

    });

    output += "\n";



    output += `## Installation\n\n`;

    output += "```bash\n";
    output += "npm install\n";
    output += "npm start\n";
    output += "```\n\n";



    output += `## Generated By TACIC\n`;

    return output;
}

module.exports = {
    generateReadme
};